### ISSUE TITLE
Walmart joke image is distorted

### ISSUE THREAD

**Issue by ardeche07** [gravitational/downtime#18]
Is there a way to fix the image so it is not distorted? I can grab a new screenshot if needed.
![image](https://user-images.githubusercontent.com/87366358/149541144-c23fd104-ed41-493c-9172-ec7f7442a76c.png)

**Comment by C-STYR** [comment]
@ardeche07 all screenshots need to be in the proper aspect ratio natively or they'll be a little distorted.  You can crop the original, but it will look strange because unless you resize your browser you'll be losing an edge...
