### ISSUE TITLE
Update photo of Barnes and Noble

### ISSUE THREAD

**Issue by ardeche07** [gravitational/downtime#32]
This is the actual local Barnes and Noble where Kelsey Hightower lives.   Can you please update that image with this one?

https://upload.wikimedia.org/wikipedia/commons/c/cc/Clackamas_Town_Center_Oct_09.jpg

Thanks!

Michael

**Comment by deliaconstantino** [comment]
@ardeche07 verifying that the above image isn't too grainy.
1. Here is the Keksey Hightower neighborhood image:
<img width="1218" alt="Screen Shot 2022-01-27 at 2 04 46 PM" src="https://user-images.githubusercontent.com/70108137/151426679-12c5f67f-4a3a-4db7-9e0f-66c5f835e6db.png">

2. Here is the current Barnes and Noble image:
<img width="1223" alt="Screen Shot 2022-01-27 at 2 04 15 PM" src="https://user-images.githubusercontent.com/70108137/151426537-ecbc0481-3ddb-44ba-8560-fb3fef90872f.png">

Let me know if you like option 1 or 2. Thanks!

**Comment by ardeche07** [comment]
It's fine. The image is supposed to look like a bad cell phone picture.
