### ISSUE TITLE
When a new joke posts, pipe it to our #downtimedotdev slack channel

### ISSUE THREAD

**Issue by ardeche07** [gravitational/downtime#38]
We can probably do this via a twitter plugin. Maybe I can even figure it out myself.

**Comment by deliaconstantino** [comment]
@Michael do you want this to subscribe to Twitter or to the downtime.dev website?

It looks like we could very easily set up an RSS feed for downtime.dev following these instructions from [slack](https://slack.com/help/articles/218688467-Add-RSS-feeds-to-Slack). This feature is apparently built in to all Slack plans so we'd just need to set it up.

**Comment by ardeche07** [comment]
Yes, that seems like a good way to do it! Can you check and see if that is how we are doing for the teleport blog currently?  We can just copy that. 

Thanks!

Michael Ferranti
Chief Marketing Officer
goteleport.com <http://goteleport.com/>

The easiest, most secure way to access all your infrastructure.

**Comment by deliaconstantino** [comment]
Yes, I will take a look at that. 

Putting my note back as I'd deleted it:
(It looks like we could very easily set up an RSS feed for downtime.dev following these instructions from slack https://slack.com/help/articles/218688467-Add-RSS-feeds-to-Slack. This feature is apparently built in to all Slack plans so we'd just need to set it up.)
