### ISSUE TITLE
Add Twitter pixel to the website

### ISSUE THREAD

**Issue by halyna-y** [gravitational/downtime#68]
Please add this Twitter pixel for the downtimedev handle to the website.

```
!-- Twitter universal website tag code -->
<script>
!function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);
},s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
// Insert Twitter Pixel ID and Standard Event data below
twq('init','o7ns3');
twq('track','PageView');
</script>
<!-- End Twitter universal website tag code -->
```

Referring to this thread on Slack: https://gravitational.slack.com/archives/C02V29GFQTU/p1644356586886269

**Comment by halyna-y** [comment]
@C-STYR wasn't able to assign this to you right away.
<img width="507" alt="Screen Shot 2022-02-08 at 3 25 15 PM" src="https://user-images.githubusercontent.com/84700204/153092950-5d9341a9-0529-4116-abcf-f8b77fce6fa6.png">

**Comment by C-STYR** [comment]
@halyna-y different repo, different rules.  Just click `Assignees` for the dropdown menu and select.

**Comment by C-STYR** [comment]
Changed permissions and added the marketing team, it should work now...

**Comment by C-STYR** [comment]
<img width="1152" alt="Screen Shot 2022-02-09 at 11 59 30 AM" src="https://user-images.githubusercontent.com/73362670/153289058-7492e429-c6b5-4394-9ddc-0059415f62f6.png">
Added via GTM.
