### ISSUE TITLE
Integrate Contentful

### ISSUE THREAD

**Issue by C-STYR** [gravitational/downtime#69]
Set up the Contentful CMS with downtime.dev in order to allow non-developers to publish daily jokes. 

We will probably need to discuss this in depth, but Alex would like you to start [here](https://www.youtube.com/watch?v=m9mNsYJbkNg&list=PL4cUxeGkcC9jClk8wl1yJcN3Zlrr8YSA1).

**Comment by deliaconstantino** [comment]
Updated to dos for Contentful V2:
- Remove embed code in contentful
- Make sure single pages have og and twitter og images
- remove # id from each card and field in contentful
- Update share link to use new slug URL for that specific joke

**Comment by C-STYR** [comment]
Moved to Asana
